name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc
    - name: Build C Program
      run: gcc -o Programme src/Programme.c
    - name: Execute Program
      run: ./Programme
